# 每次 github 提交都会执行

name: Push Developer CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]   
    paths-ignore: ["**/*.txt","**/*.md", "LICENSE", "**/*.xmind", "**/*.doc", "**/*.docx", "**/*.yml", "**/*.ymal"]
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:

    strategy:
      matrix:
        configuration: [Debug]

    # The type of runner that the job will run on
    runs-on: windows-latest    
    
    env:
      Solution_Name: Action-wpf

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
     
      # Install the .NET Core workload
      - name: Install .NET Core
        uses: actions/setup-dotnet@v2
        with:
            dotnet-version: 6.0.x            

      # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2 

      - name:  Setup Node
        uses: actions/setup-node@v3
        with:
            node-version: 14
      
      # 添加 Devexpress 源
      - name: add nuget source
        run: dotnet nuget add source https://nuget.devexpress.com/OV9cpAjb46fbHHwFLwIOF8huukkKPG8RpRVhf1l732cLnMXYXr/api

      # Restore the application to populate the obj folder with RuntimeIdentifiers
      - name: Restore the application
        run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
        env:
          Configuration: ${{ matrix.configuration }}

     # build
      - name: build 
        run: msbuild  $env:Solution_Name

      - name: notify build failure
        uses: tokorom/action-slack-incoming-webhook@main
        env:
             INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
             text: "build failte, check actions log"
             attachments: |
                [
                    {
                        "color": "good",
                        "author_name": "${{ github.actor }}",
                        "author_icon": "${{ github.event.sender.avatar_url }}",                 
                        "fields": [
                                        {
                                            "title": "Commit User",
                                            "value": "${{ github.event.commits[0].committer.name}}"
                                        },
                                        {
                                            "title": "Commit Message",
                                            "value": "${{ github.event.commits[0].message }}"
                                        },
                                        {
                                            "title": "GitHub Actions URL",
                                            "value": "${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}"
                                        }
                                ]
                    }
                ]
        if: failure()

      
      - name: notify build success
        uses: tokorom/action-slack-incoming-webhook@main
        env:
             INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
             text: "build success"
             attachments: |
                [
                    {
                        "color": "good",
                        "author_name": "${{ github.actor }}",
                        "author_icon": "${{ github.event.sender.avatar_url }}",                 
                        "fields": [
                                        {
                                            "title": "Commit User",
                                            "value": "${{ github.event.commits[0].committer.name}}"
                                        },
                                        {
                                            "title": "Commit Message",
                                            "value": "${{ github.event.commits[0].message }}"
                                        },
                                        {
                                            "title": "GitHub Actions URL",
                                            "value": "${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}"
                                        }
                                ]
                    }
                ]

        if: success()